name: Build and Test macOS Application

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name artnet2midi.app artnet2midi.py

    - name: Test application startup
      run: |
        python test_artnet2midi.py

    - name: Display stdout log
      run: |
        echo "stdout log:"
        cat stdout.log

    - name: Display stderr log
      run: |
        echo "stderr log:"
        cat stderr.log

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          stdout.log
          stderr.log

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: artnet2midi-macos
        path: dist/artnet2midi.app
